#!/usr/bin/env bash
# Display record types of subdomains
# Usage: ./0-world_wide_web <domain> <subdomain>

domain_information () {
  echo "$2 $(dig "$2"."$1" +noall +answer)" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
