#!/usr/bin/env bash
# Display record types of subdomains
# Usage: ./0-world_wide_web <domain> <subdomain>

# Function to get and show domain info
show_domain_info () {
    echo "$2 $(dig $2.$1 +noall +answer | cut -f4,5)" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 2 ]
then
    show_domain_info $1 $2
elif [ $# -eq 1 ]
then
    show_domain_info $1 $2
fi
