#!/usr/bin/env bash
# Install NGINX

# Instal nginx
sudo apt update
sudo apt install -y nginx

# Create default nginx folder
sudo mkdir -p /var/www/html

# Create default index.html file
sudo touch /var/www/html/index.html

# Change ownership of file and directories to current user
# in order to edit the file.
sudo chown -R "$USER":"$USER" /var/www/html/index.html

# Append hello world to file
echo "Hello World!" > /var/www/html/index.html

#
sudo ufw allow 'Nginx HTTP'

# start nginx server
sudo service nginx restart
