#!/usr/bin/env bash
# Script to set user nginx as NGINX service user running on port 8080
# Usage: 1-run_nginx_as_nginx <>

# Set nginx as default user in nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change default port 80 to 8080
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default

# Kill apache running on port 8080
pkill -f apache2

# Stop current running nginx instance
sudo service nginx stop

# Restart nginx server as nginx user
sudo -u nginx service nginx start
